// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using LazyLoading_Pattern_WebAPI.DataAccess;
using System;
using System.Collections.Generic;

namespace LazyLoading_Pattern_WebAPI.DatabaseFirst
{
    public partial class WeatherInformation:IEntity
    {
        public int IdWeather { get; set; }
        public string Status { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public DateTime? When { get; set; }
        public string Description { get; set; }
    }
}